service: serverless-boilerplate

custom: 
  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage}

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  memorySize: 512
  environment:
    MONGODB_CONNECTION_STRING: ${file(env.${self:custom.currentStage}.yml):MONGODB_CONNECTION_STRING}

functions:
  - ${file(routes/create.yml)}
  - ${file(routes/read.yml)}
  - ${file(routes/update.yml)}
  - ${file(routes/delete.yml)}

plugins:
  - serverless-offline
